### ISSUE TITLE
Add nuisance password to site

### ISSUE THREAD

**Issue by fgassert** [PReP-Team/prep-prototype#7]
Once we put logos on the site, we should put a basic password on it to prevent it from getting too public before the partners sign off.

The password does not have to be exceptionally secure, and should be cookied for returning visitors.

**Comment by apfister** [comment]
@d4weed mind if i ask how you secured the http://vizzuality.github.io/WRW-Prototype/ site? if you have an easy way of spinning up simple auth for these types of situations, i'd love to hear it. thanks!

**Comment by d4weed** [comment]
Hey @apfister,

We just have a variable encoded in base64 (name and value) that is used to compare the input, and we then write a cookie for persistence.

since it's just about not having it explicitly public it's secure enough (someone digging in the code could break it, but it's not a big issue given it's public anyway)

**Comment by fgassert** [comment]
Yeah, I think you just need a short module in your main app init that checks for a cookie and redirects to a login page, and the login page can check the password on the client side and write the cookie.

Something like this, but redirect instead of a blocking div https://github.com/fgassert/insec.js/blob/master/insec.js

**Comment by apfister** [comment]
the password is now `password123`

**Comment by apfister** [comment]
i've added a password to the site. how should we distribute it?

**Comment by fgassert** [comment]
Excellent. We can just email folks when they ask for it.
